language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"
env:
  - DJANGO_VERSION=1.4.16
  - DJANGO_VERSION=1.6.8
  - DJANGO_VERSION=1.7.1
install:
    - pip install flake8 --use-mirrors
    - pip install -e .
    - pip uninstall --yes django
    - pip install -q Django==$DJANGO_VERSION
    - pip install coveralls
before_script:
    flake8 --statistics src/inkpy
script:
  coverage run --source=inkpy  --omit="*__init__*" src/inkpy/tests/tests.py -v
after_success:
  coveralls
