language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"
install:
    - pip install flake8 --use-mirrors
    - pip install -e .
    - pip install coveralls
before_script:
    flake8 --statistics src/inkpy
script:
  coverage run --source=inkpy  --omit="*__init__*" src/inkpy/tests/tests.py -v
after_success:
  coveralls
